spring.application.name=BankAccount
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/CGBANK

# Confir server makeing properties externilized
spring.config.import=optional:configserver:http://localhost:8888/

# PostgreSQL Database Configuration
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/CGBANK
#
#
## JPA / Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## PostgreSQL Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

